# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 586)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("/* (Label at top) Label Stylesheet */\n"
"QLabel {\n"
" qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
" border: 1px solid gray;\n"
"background-color : white;\n"
"}\n"
"\n"
"/* End Label Stylesheet */")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_C = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_C.setGeometry(QtCore.QRect(20, 80, 93, 91))
        self.pushButton_C.setStyleSheet("/* (Clear,+/-,%,. buttons) Unary Operations Buttons Stylesheet */\n"
                                        "QPushButton {\n"
                                        " background-color: rgb(215, 215, 215);\n"
                                        " border: 1px solid gray;\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                        "                   stop: 0 #BEBEBE, stop: 1 #D7D7D7);\n"
                                        "}\n"
                                        "/* End Unary Operations Buttons Stylesheet */")
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_plus_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_plus_minus.setGeometry(QtCore.QRect(120, 80, 93, 91))
        self.pushButton_plus_minus.setStyleSheet("/* (Clear,+/-,%,. buttons) Unary Operations Buttons Stylesheet */\n"
                                                 "QPushButton {\n"
                                                 " background-color: rgb(215, 215, 215);\n"
                                                 " border: 1px solid gray;\n"
                                                 "}\n"
                                                 "QPushButton:pressed {\n"
                                                 "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                                 "                   stop: 0 #BEBEBE, stop: 1 #D7D7D7);\n"
                                                 "}\n"
                                                 "/* End Unary Operations Buttons Stylesheet */")
        self.pushButton_plus_minus.setObjectName("pushButton_plus_minus")
        self.pushButton_percent = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_percent.setGeometry(QtCore.QRect(220, 80, 93, 91))
        self.pushButton_percent.setStyleSheet("/* (Clear,+/-,%,. buttons) Unary Operations Buttons Stylesheet */\n"
                                              "QPushButton {\n"
                                              " background-color: rgb(215, 215, 215);\n"
                                              " border: 1px solid gray;\n"
                                              "}\n"
                                              "QPushButton:pressed {\n"
                                              "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                              "                   stop: 0 #BEBEBE, stop: 1 #D7D7D7);\n"
                                              "}\n"
                                              "/* End Unary Operations Buttons Stylesheet */")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.pushButton_divide = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(320, 80, 93, 91))
        self.pushButton_divide.setStyleSheet("/* (Orange buttons) Operations Buttons Stylesheet */\n"
                                             "QPushButton {\n"
                                             " background-color: rgb(255, 151, 57);\n"
                                             " color: white;\n"
                                             " border: 1px solid gray;\n"
                                             "}\n"
                                             "QPushButton:pressed {\n"
                                             "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                             "                   stop: 0 #FF7832, stop: 1 #FF9739);\n"
                                             "}\n"
                                             "/* (Label at top) Label Stylesheet */")
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 180, 91, 91))
        self.pushButton_7.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
                                        "QPushButton {\n"
                                        "  border: 1px solid gray;\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                        "                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                        "}\n"
                                        "/* End Digits 0-9 Stylesheet */")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_mul = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_mul.setGeometry(QtCore.QRect(320, 180, 93, 91))
        self.pushButton_mul.setStyleSheet("/* (Orange buttons) Operations Buttons Stylesheet */\n"
                                          "QPushButton {\n"
                                          " background-color: rgb(255, 151, 57);\n"
                                          " color: white;\n"
                                          " border: 1px solid gray;\n"
                                          "}\n"
                                          "QPushButton:pressed {\n"
                                          "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                          "                   stop: 0 #FF7832, stop: 1 #FF9739);\n"
                                          "}\n"
                                          "/* (Label at top) Label Stylesheet */")
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(222, 180, 91, 91))
        self.pushButton_9.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
                                        "QPushButton {\n"
                                        "  border: 1px solid gray;\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                        "                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                        "}\n"
                                        "/* End Digits 0-9 Stylesheet */")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(120, 180, 93, 91))
        self.pushButton_8.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
                                        "QPushButton {\n"
                                        "  border: 1px solid gray;\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                        "                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                        "}\n"
                                        "/* End Digits 0-9 Stylesheet */")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 280, 93, 91))
        self.pushButton_4.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
                                        "QPushButton {\n"
                                        "  border: 1px solid gray;\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                        "                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                        "}\n"
                                        "/* End Digits 0-9 Stylesheet */")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(320, 280, 93, 91))
        self.pushButton_minus.setStyleSheet("/* (Orange buttons) Operations Buttons Stylesheet */\n"
                                            "QPushButton {\n"
                                            " background-color: rgb(255, 151, 57);\n"
                                            " color: white;\n"
                                            " border: 1px solid gray;\n"
                                            "}\n"
                                            "QPushButton:pressed {\n"
                                            "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                            "                   stop: 0 #FF7832, stop: 1 #FF9739);\n"
                                            "}\n"
                                            "/* (Label at top) Label Stylesheet */")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 280, 93, 91))
        self.pushButton_6.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
                                        "QPushButton {\n"
                                        "  border: 1px solid gray;\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                        "                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                        "}\n"
                                        "/* End Digits 0-9 Stylesheet */")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 280, 93, 91))
        self.pushButton_5.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"QPushButton {\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"/* End Digits 0-9 Stylesheet */")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 380, 93, 91))
        self.pushButton_1.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"QPushButton {\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"/* End Digits 0-9 Stylesheet */")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(320, 380, 93, 91))
        self.pushButton_plus.setStyleSheet("/* (Orange buttons) Operations Buttons Stylesheet */\n"
"QPushButton {\n"
" background-color: rgb(255, 151, 57);\n"
" color: white;\n"
" border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                   stop: 0 #FF7832, stop: 1 #FF9739);\n"
"}\n"
"/* (Label at top) Label Stylesheet */")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 380, 93, 91))
        self.pushButton_3.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"QPushButton {\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"/* End Digits 0-9 Stylesheet */")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 380, 93, 91))
        self.pushButton_2.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"QPushButton {\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"/* End Digits 0-9 Stylesheet */")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_equal = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_equal.setGeometry(QtCore.QRect(320, 480, 93, 91))
        self.pushButton_equal.setStyleSheet("/* (Orange buttons) Operations Buttons Stylesheet */\n"
"QPushButton {\n"
" background-color: rgb(255, 151, 57);\n"
" color: white;\n"
" border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                   stop: 0 #FF7832, stop: 1 #FF9739);\n"
"}\n"
"/* (Label at top) Label Stylesheet */")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_dot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_dot.setGeometry(QtCore.QRect(220, 480, 93, 91))
        self.pushButton_dot.setStyleSheet("/* (Clear,+/-,%,. buttons) Unary Operations Buttons Stylesheet */\n"
"QPushButton {\n"
" background-color: rgb(215, 215, 215);\n"
" border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                   stop: 0 #BEBEBE, stop: 1 #D7D7D7);\n"
"}\n"
"/* End Unary Operations Buttons Stylesheet */")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_0 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(20, 480, 191, 91))
        self.pushButton_0.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"QPushButton {\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                   stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"/* End Digits 0-9 Stylesheet */")
        self.pushButton_0.setObjectName("pushButton_0")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_C.setText(_translate("MainWindow", "c"))
        self.pushButton_plus_minus.setText(_translate("MainWindow", "+/-"))
        self.pushButton_percent.setText(_translate("MainWindow", "%"))
        self.pushButton_divide.setText(_translate("MainWindow", "/"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_mul.setText(_translate("MainWindow", "X"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
